<style>
    #message-notice
    {
        position: relative;
        padding: 1.5rem 0 1.5rem 4.5rem;
        border: 1px solid #d1d1d1;
        border-radius: 3px;
        background: #fffbbb;
    }
    #message-notice:before
    {
        font-family: 'Admin Icons';
        font-size: 1.9rem;
        position: absolute;
        top: 50%;
        left: 1rem;
        content: '\e623';
        -webkit-transform: translate(0, -50%);
        -ms-transform: translate(0, -50%);
        transform: translate(0, -50%);
        color: #eb5202;
        border: 0;
        background: none;
    }
</style>

<div id="message-notice">
    A new version of Log Cleaner for Magento 2 (v<?= $block->getLatestVersion() ?>) is available.
    Download update from the <a href="<?= $block->getRepositoryUrl() ?>" target="_blank">project repository</a> to stay up-to-date.
    See extension
    <a id="change-logs" onclick href="#">change log</a>
    for more details.
</div>
<div id="change-logs-list"></div>

<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function($, modal) {
        $('#message-notice #change-logs').click(function(e) {
            e.preventDefault();

            // alert('change logs');


            $.ajax({
                url: '<?= $block->getUrl('dtlogcleaner/module/changeLogs'); ?>',
                showLoader: true,
                method: 'GET',
                success: function(data) {
                    $('#change-logs-list').html(data.html);

                    var params = {
                        type: 'slide',
                        responsive: true,
                        innerScroll: true,
                        title: 'Change Logs',
                        buttons: [{
                            text: $.mage.__('Close'),
                            class: '',
                            click: function () {
                                this.closeModal();
                                $('#change-logs-list').html('');
                            }
                        }, {
                            text: $.mage.__('Open repository'),
                            class: 'action-primary',
                            click: function () {
                                window.open('<?= $block->getRepositoryUrl() ?>', '_blank').focus()
                            }
                        }]
                    };

                    var popup = modal(params, $('#change-logs-list'));

                    $('#change-logs-list').modal("openModal");
                }.bind(this)
            });



        });
    });

</script>




